### ISSUE TITLE
Showing error

### ISSUE THREAD

**Issue by mervinnnlim** [maximousblk/callow#37]
Why is it showing error? 

```
$ python3 callow.py               

     ____      _ _                                                                                           
    / ___|__ _| | | _____      __                                                                            
   | |   / _` | | |/ _ \ \ /\ / /                                                                            
   | |__| (_| | | | (_) \ V  V /                                                                             
    \____\__,_|_|_|\___/ \_/\_/                                                                              
                                                                                                             
[#] maximousblk/callow@v1.3                                                                                  


[~] Target login page (http/https only): https://callow.now.sh/sandbox/                                      
[#] Checking if site is accessible [OK]
                                                                                                             
[~] Username input selector: #username
[~] Password input selector: #password
[~] Target username: testuser
[~] Password dictionary: pass.txt
Traceback (most recent call last):
  File "/home/kali/Desktop/callow-master/callow.py", line 125, in <module>
    wizard()
  File "/home/kali/Desktop/callow-master/callow.py", line 70, in wizard
    crack(username, usersel, passsel, passlist, website) # Start the attack
  File "/home/kali/Desktop/callow-master/callow.py", line 89, in crack
    browser = webdriver.Chrome(options=chrome_options)
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 106, in start
    self.assert_process_still_running()
  File "/home/kali/.local/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 117, in assert_process_still_running
    return_code = self.process.poll()
AttributeError: 'Service' object has no attribute 'process'

```

**Comment by mervinnnlim** [comment]
i have found the issue and its solved.
